version: '3.3'
services:
  rethinkdb:
    image: rethinkdb:2.3
    network_mode: host
    command: ["rethinkdb", "--bind", "all"]
    restart: always
    volumes:
      - ""
  stflocal:
    network_mode: host
    depends_on:
      - rethinkdb
      - adb
    image: openstf/stf
    restart: always
    command: ["stf", "local", "--public-ip", "${PUBLICIP}"]
  adb:
    image: sorccu/adb
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
